#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

docker build -t frontend:v1 ./frontend/ &
docker build -t backend:v1 ./backend/

docker tag frontend:v1 mykubecr.azurecr.io/frontend:v1
docker tag backend:v1 mykubecr.azurecr.io/backend:v1 

docker push mykubecr.azurecr.io/backend:v1 &
docker push mykubecr.azurecr.io/frontend:v1
