FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine AS build-env
WORKDIR /app

# Copy csproj 
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:latest
WORKDIR /app
COPY --from=build-env /app/out .
ENV ASPNETCORE_URLS http://*:80
# Create local file?
EXPOSE 80
ENTRYPOINT ["dotnet", "Docker Local.dll"]

# docker run -d testapp:v1 -p 80:80/tcp --mount source=C:\Volume,target=/volume
# Docker client verwenden...
